name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. GitHub Container Registry 로그인
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build # 배포는 빌드가 성공한 후에 실행
    permissions:
      contents: read
      packages: write

    steps:
      # 1. GitHub Actions의 IP를 EC2 보안 그룹에 추가 (SSH 인바운드 규칙)
      - name: Add SSH inbound rule to EC2 security group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-00238cd34b57d6565 \
            --protocol tcp \
            --port 22 \
            --cidr $(curl -s https://checkip.amazonaws.com)/32
        # GitHub Actions IP를 보안 그룹에 추가하여 SSH 접근 허용

      # 2. EC2로 배포 작업 수행
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > SSH_PRIVATE_KEY.pem
          chmod 600 SSH_PRIVATE_KEY.pem
          ssh -i SSH_PRIVATE_KEY.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd clab
            docker pull ghcr.io/connects-lab/clab-api_user:latest
            docker compose down
            docker compose up -d
          EOF

      # 3. SSH 인바운드 규칙 제거 (보안 그룹에서 SSH 접근 차단)
      - name: Remove SSH inbound rule from EC2 security group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id sg-00238cd34b57d6565 \
            --protocol tcp \
            --port 22 \
            --cidr $(curl -s https://checkip.amazonaws.com)/32
